- name: Install Apache and PHP packages
  tags: apache,redhat,httpd
  package:
    name: 
      - "{{ apache_package }}"
      - "{{ php_package }}"
    state: latest
  notify: Apache and PHP instaled


- name: Start httpd server (RedHat)
  tags: apache,redhat,httpd
  service:
    name: httpd
    state: started
    enabled: yes
  notify: httpd started
  when: ansible_os_family == "RedHat"

- name: copy default html files
  tags: apache,redhat,httpd
  copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644