- name: add ssh key to user
  authorized_key:
    user: andreja
    key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDVTSsyHb7bDUWQLupquecXnAiR/TLfQVr2mWtfVZXPRWmqG/sdGj2u2rvQOR1ox9rm9Dp2/jniuOtQR5Di3by7ISDNV2psW/dDCBS+NYfu1aFP9B+2jejIaWOO9aKS4VeZEVsMuYVOSsnzfH0bk1Lwpx9KRznXAljW6+fzVNLcgsAvNNdn21j7octv6I289Q5Q04fxmRsOCs5s2i7NWvgbr1DCN6/xURO6XNL93DbrggFXj/5mPNq1izRhOcrlJCur1DDTHa4VFfI+pUG3uII98UkQVo7ojdtiKo0wwfzMSKMtqysyKR2ZHX+d2DtmpCe0isAmalQwxtsdEniU5dvx ec2-user@ansible-engine"